import { Dimensions, StyleSheet } from "react-native";
import colors from "../../../styles/colors";

export default StyleSheet.create({
    container:{
        flex:1,
        backgroundColor:"black"
    },
    title:{
      color:"white",
      fontSize:18,
      marginLeft:15,
      maxWidth:280
    },
    author:{
      color:colors.darkgray,
      fontSize:15,
      marginLeft:15,
      maxWidth:280,
      marginTop:2
    },
    image:{
      height:130,
      width:80,
  },
  upper_container:{
    flexDirection:"row",
    margin:20
  },
  seperator:{
    borderWidth:0.3,
    borderColor:colors.darkgray
  },
  category:{
    color:colors.darkgray,
    fontSize:15,
    marginLeft:15,
    maxWidth:280,
    marginTop:10
  },
  description:{
    marginBottom:100,
    color:colors.lightgray,
    fontSize:15,
    marginLeft:15,
    maxWidth:Dimensions.get("window").width-50,
    marginTop:10,
    alignSelf:"center",
    justifyContent:"center"
  },
  description_title:{
    marginLeft:32,
    color:"white",
    fontSize:20,
    marginTop:10
  },
  back_container:{
  margin:10,
  flexDirection:"row",
  },
  back_text:{
    marginLeft:5,
    color:"white",
    fontSize:15
  },
  button_container:{
    flexDirection:"row",
    justifyContent:"center"
  }
})